title: Sabertoot
description: A Mastodon Client Library for Java and Kotlin
theme: just-the-docs

url: https://andregasser.github.io/sabertoot-doc

aux_links:
  Template Repository: https://github.com/andregasser/sabertoot-doc
